def add_lineno(str):
    """Add line number to the given code string. Pygments has some issue with its line
    numbers when the browser is resized. This line number is more foolproof"""
    lines = str.strip().split("\n")
    line_tags = "<div class=\"lineno\"><pre>\n"
    for i in range(len(lines) - 1):  # -1 to not count </pre></div> closure generated by pygments
        line_tags += "<span class=\"linenumeric\">%d</span>\n" % (i+1)
    line_tags += "</pre></div>"
    return line_tags + "\n" + str
